server:
  shutdown: graceful

spring:
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  jackson:
    default-property-inclusion: non_null

  web:
    resources:
      static-locations: classpath:/static/
