name: build-docker-image
on: [push]

jobs:
  java-springboot-tomcat:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./java+springboot+tomcat
    steps:
      - uses: actions/checkout@v2
        name: Set up JDK 17

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle        
        run: ./gradlew build --no-daemon

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./java+springboot+tomcat
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/puppeteer-executor:latest